const churches = [
  {
    id: 1, city: "羅馬", day: 2,
    name: "聖伯多祿鎖鏈堂",
    nameEn: "San Pietro in Vincoli",
    description: "收藏米開朗基羅曠世巨作《摩西像》——摩西頭上的「角」源自拉丁文聖經翻譯錯誤，成為藝術史上最著名的「美麗錯誤」。清晨人少，可獨享大師雕塑。",
    address: "Piazza di San Pietro in Vincoli, 4a, 00184 Roma",
    hours: "每日 8:00–12:20 / 15:00–18:50",
    suggestedTime: "Day 2 早上 8:30（✅ 開放）",
    ticket: "免費",
    mustSee: "米開朗基羅《摩西像》",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/San_Pietro_in_Vincoli_-_esterno.jpg/960px-San_Pietro_in_Vincoli_-_esterno.jpg",
    tags: ["免費", "米開朗基羅"]
  },
  {
    id: 2, city: "羅馬", day: 2,
    name: "聖克萊門特教堂",
    nameEn: "Basilica di San Clemente",
    description: "獨一無二的三層「時光機」教堂——地面 12 世紀中世紀教堂 → 地下 4 世紀早期基督教會 → 最深層 1 世紀羅馬密特拉神殿，還能聽到地下水流聲。",
    address: "Via Labicana, 95, 00184 Roma",
    hours: "週一至六 9:00–12:30 / 15:00–18:00；週日 12:15–18:00",
    suggestedTime: "Day 2 中午 12:00（✅ 開放）",
    ticket: "上層免費；地下挖掘區 €10",
    mustSee: "三層地下遺跡（密特拉神殿）",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Basilica_di_San_Clemente_al_Laterano_-_esterno.jpg/960px-Basilica_di_San_Clemente_al_Laterano_-_esterno.jpg",
    tags: ["收費", "地下遺跡", "親子"]
  },
  {
    id: 3, city: "羅馬", day: 2,
    name: "耶穌教堂",
    nameEn: "Church of the Gesù",
    description: "全世界第一座耶穌會教堂，巴洛克風格的鼻祖。天花板壁畫《耶穌之名的勝利》是透視幻覺畫的巔峰——難以分辨何處是畫、何處是雕塑。",
    address: "Piazza del Gesù, 54, 00186 Roma",
    hours: "每日 7:00–12:30 / 16:00–19:45",
    suggestedTime: "Day 2 下午 16:00（✅ 開放）",
    ticket: "免費",
    mustSee: "天花板壁畫《耶穌之名的勝利》",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Jesus_Church.jpg/960px-Jesus_Church.jpg",
    tags: ["免費", "巴洛克", "幻覺畫"]
  },
  {
    id: 4, city: "羅馬", day: 4,
    name: "聖母大殿",
    nameEn: "Santa Maria Maggiore",
    description: "羅馬四大宗座聖殿之一，建於 5 世紀。內部華麗的 13 世紀鑲嵌畫與金色天花板（據說黃金來自哥倫布帶回的美洲）。距 Termini 車站步行 5 分鐘，搭火車前可順訪。",
    address: "Piazza di Santa Maria Maggiore, 42, 00185 Roma",
    hours: "每日 7:00–18:45",
    suggestedTime: "Day 4 早上搭火車前（距 Termini 步行 5 分鐘）",
    ticket: "免費",
    mustSee: "13 世紀鑲嵌畫、黃金天花板",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Basilica_di_Santa_Maria_Maggiore_-_Roma.jpg/960px-Basilica_di_Santa_Maria_Maggiore_-_Roma.jpg",
    tags: ["免費", "宗座聖殿", "備選"]
  },
  {
    id: 5, city: "佛羅倫斯", day: 4,
    name: "新聖母大殿",
    nameEn: "Santa Maria Novella",
    description: "就在 SMN 火車站正對面！正立面是文藝復興幾何美學的典範。內部有馬薩喬的《聖三位一體》——人類藝術史上第一幅使用數學線性透視法的繪畫，徹底改變了西洋美術的方向。",
    address: "Piazza di Santa Maria Novella, 18, 50123 Firenze",
    hours: "週一至四 9:00–17:30；週五 11:00–17:30；週六 9:00–17:00；週日 13:00–17:00",
    suggestedTime: "Day 4 上午 11:15（✅ 開放，火車站正對面）",
    ticket: "€7.50（含西班牙禮拜堂等修道院區域）",
    mustSee: "馬薩喬《聖三位一體》、吉蘭達約壁畫",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Florence%2C_Santa_Maria_Novella%2C_facade.jpg/960px-Florence%2C_Santa_Maria_Novella%2C_facade.jpg",
    tags: ["收費", "文藝復興", "透視法"]
  },
  {
    id: 6, city: "佛羅倫斯", day: 5,
    name: "聖十字大殿",
    nameEn: "Basilica di Santa Croce",
    description: "人稱「義大利的榮耀殿堂」，米開朗基羅、伽利略、馬基維利、羅西尼等巨匠皆長眠於此。內部 16 座家族禮拜堂保留喬托壁畫，是一本立體的義大利文藝復興史教科書。",
    address: "Piazza di Santa Croce, 16, 50122 Firenze",
    hours: "週一至六 9:30–17:30；週日 12:30–17:45",
    suggestedTime: "Day 5 下午 15:00（✅ 開放）",
    ticket: "€8",
    mustSee: "米開朗基羅墓、伽利略墓、喬托壁畫",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Basilica_di_Santa_Croce_%2812437%29.jpg/960px-Basilica_di_Santa_Croce_%2812437%29.jpg",
    tags: ["收費", "名人墓", "喬托"]
  },
  {
    id: 7, city: "佛羅倫斯", day: 6,
    name: "聖米尼亞託大殿",
    nameEn: "San Miniato al Monte",
    description: "佛羅倫斯最美的羅馬式教堂，11 世紀的白色與綠色大理石幾何立面在夕陽下如發光寶石。坐落山丘頂，俯瞰全市。內部中世紀黃道帶大理石地板令人驚嘆。",
    address: "Via delle Porte Sante, 34, 50125 Firenze",
    hours: "週一至六 9:30–13:00 / 15:00–19:00；週日 15:00–19:00",
    suggestedTime: "Day 6 下午 16:30（✅ 開放）",
    ticket: "免費",
    mustSee: "11 世紀羅馬式立面、黃道帶地板、全景",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/San_Miniato_al_Monte%2C_exterior%2C_Florencia%2C_Italia%2C_2019_01_cropped.jpg/960px-San_Miniato_al_Monte%2C_exterior%2C_Florencia%2C_Italia%2C_2019_01_cropped.jpg",
    tags: ["免費", "羅馬式", "夕陽", "全景"]
  },
  {
    id: 8, city: "比薩", day: 6,
    name: "比薩主教座堂",
    nameEn: "Pisa Cathedral (Duomo di Pisa)",
    description: "奇蹟廣場的真正主角——斜塔只是它的鐘樓！1064 年建成，黑白大理石交錯的 Pisan Romanesque 風格。內部奇馬布埃馬賽克《基督榮耀》是藝術家生前最後作品。",
    address: "Piazza del Duomo, 56126 Pisa",
    hours: "4–9月：每日 10:00–20:00",
    suggestedTime: "Day 6 上午 9:30（10:00 開門入內）",
    ticket: "免費（需在洗禮堂旁領入場券）",
    mustSee: "奇馬布埃馬賽克、皮薩諾講道壇",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Pisa_-_Cattedrale_da_Battistero_02.jpg/960px-Pisa_-_Cattedrale_da_Battistero_02.jpg",
    tags: ["免費", "羅馬式", "奇蹟廣場"]
  },
  {
    id: 9, city: "比薩", day: 6,
    name: "比薩洗禮堂",
    nameEn: "Pisa Baptistery",
    description: "義大利最大的洗禮堂，圓周 107 公尺。最神奇的是音響效果——工作人員每隔 30 分鐘示範回音演唱，單音可持續 10 秒以上，小朋友會看呆。尼古拉·皮薩諾的講道壇（1260 年）是文藝復興雕塑的起點。",
    address: "Piazza del Duomo, 56126 Pisa（大教堂正前方）",
    hours: "每日 9:00–19:00",
    suggestedTime: "Day 6 上午 10:00 後（✅ 開放）",
    ticket: "奇蹟廣場聯票 €10（含洗禮堂、墓園、博物館）",
    mustSee: "整點回音示範、皮薩諾講道壇",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/CampodeiMiracoliPisa.jpg/960px-CampodeiMiracoliPisa.jpg",
    tags: ["收費", "回音", "親子"]
  },
  {
    id: 10, city: "威尼斯", day: 7,
    name: "榮耀聖母堂",
    nameEn: "Santa Maria Gloriosa dei Frari",
    description: "威尼斯最重要的藝術教堂。提香《聖母升天》祭壇畫——威尼斯最大的油畫，紅與金的色彩爆發，是提香巔峰之作。提香本人也葬在此。卡諾瓦宏偉陵墓亦在內。",
    address: "San Polo, 3072, 30125 Venezia",
    hours: "週一至六 9:00–18:00；週日 13:00–18:00",
    suggestedTime: "Day 7 下午 16:00（✅ 開放）",
    ticket: "€5",
    mustSee: "提香《聖母升天》、提香墓、卡諾瓦陵墓",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Facade_of_Santa_Maria_Gloriosa_dei_Frari_%28Venice%29.jpg/960px-Facade_of_Santa_Maria_Gloriosa_dei_Frari_%28Venice%29.jpg",
    tags: ["收費", "提香", "威尼斯畫派"]
  },
  {
    id: 11, city: "威尼斯", day: 7,
    name: "聖若望保羅大殿",
    nameEn: "Basilica di San Zanipolo",
    description: "「威尼斯的萬神殿」——歷代總督長眠於此。世界最大的哥德式磚造教堂之一。內部有貝里尼、韋羅內塞作品。玫瑰經禮拜堂的天花板壁畫極其華麗。",
    address: "Castello, 6363, 30122 Venezia",
    hours: "週一至六 9:00–18:00；週日 12:00–18:00",
    suggestedTime: "Day 7 下午 17:00（✅ 開放，Frari 步行 10 分鐘）",
    ticket: "€3.50",
    mustSee: "歷代總督墓、玫瑰經禮拜堂、貝里尼畫作",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Exterior_of_Santi_Giovanni_e_Paolo_%28Venice%29.jpg/960px-Exterior_of_Santi_Giovanni_e_Paolo_%28Venice%29.jpg",
    tags: ["收費", "哥德式", "總督墓"]
  },
  {
    id: 12, city: "威尼斯", day: 7,
    name: "聖喬治馬焦雷教堂",
    nameEn: "San Giorgio Maggiore",
    description: "帕拉底歐文藝復興教堂，位於聖馬可廣場對面小島。鐘樓可搭電梯登頂——視野比聖馬可鐘樓更好，因為可以拍到聖馬可廣場全景的明信片角度。",
    address: "Isola di San Giorgio Maggiore, 30133 Venezia",
    hours: "每日 9:00–19:00（鐘樓至 18:30）",
    suggestedTime: "Day 7 傍晚 18:00（✅ 開放）",
    ticket: "教堂免費；鐘樓 €6",
    mustSee: "帕拉底歐建築、鐘樓全景（拍聖馬可最佳角度）",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/San_Giorgio_Maggiore_from_the_top_of_St_Mark%27s_Campanile.jpg/960px-San_Giorgio_Maggiore_from_the_top_of_St_Mark%27s_Campanile.jpg",
    tags: ["部分免費", "全景", "帕拉底歐"]
  },
  {
    id: 13, city: "威尼斯", day: 8,
    name: "安康聖母殿",
    nameEn: "Santa Maria della Salute",
    description: "威尼斯天際線最具代表性的白色大理石圓頂教堂。建於 1631 年瘟疫結束後，獻給拯救城市的聖母。巴洛克建築傑作，提香晚期作品在聖器室。從教堂階梯回望聖馬可廣場視角絕美。",
    address: "Dorsoduro, 1, 30123 Venezia",
    hours: "每日 9:00–12:00 / 15:00–17:30",
    suggestedTime: "Day 8 下午 16:00（✅ 開放）",
    ticket: "教堂免費；聖器室 €4",
    mustSee: "白色圓頂天際線、大運河口拍照",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Santa_Maria_della_Salute_from_Hotel_Monaco.jpg/960px-Santa_Maria_della_Salute_from_Hotel_Monaco.jpg",
    tags: ["部分免費", "巴洛克", "地標"]
  },
  {
    id: 14, city: "米蘭", day: 10,
    name: "恩寵聖母堂",
    nameEn: "Santa Maria delle Grazie",
    description: "聯合國世界遺產，達文西《最後的晚餐》就在修道院食堂牆上。這是世界上最著名的藝術品之一。教堂本身也是文藝復興瑰寶——布拉曼特設計的後殿穹頂極其優美。",
    address: "Piazza di Santa Maria delle Grazie, 2, 20123 Milano",
    hours: "教堂：週一至六 7:00–13:00 / 15:30–19:30；週日 7:30–12:30 / 16:00–21:00",
    suggestedTime: "Day 10 上午 9:00（教堂 ✅ 開放）",
    ticket: "教堂免費；《最後的晚餐》€15 + 預約費",
    mustSee: "達文西《最後的晚餐》（需提前 2-3 月預約）",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Santa_Maria_delle_Grazie_Milan_2013.jpg/960px-Santa_Maria_delle_Grazie_Milan_2013.jpg",
    tags: ["部分免費", "達文西", "世界遺產"]
  },
  {
    id: 15, city: "米蘭", day: 10,
    name: "聖馬烏里齊奧教堂",
    nameEn: "San Maurizio al Monastero Maggiore",
    description: "人稱「米蘭的西斯汀禮拜堂」——牆面和天花板 100% 被 16 世紀壁畫覆蓋，無一處空白。伯納迪諾·盧伊尼（達文西弟子）的作品，色彩保存驚人地完好。遊客極少，是米蘭最被低估的寶藏。",
    address: "Corso Magenta, 15, 20123 Milano",
    hours: "週二至日 10:00–17:30（週一休）",
    suggestedTime: "Day 10 上午 10:00（✅ 開放）",
    ticket: "免費",
    mustSee: "全覆蓋 16 世紀壁畫（米蘭的西斯汀）",
    image: "https://upload.wikimedia.org/wikipedia/commons/9/9e/095MilanoSMaurizio.JPG",
    tags: ["免費", "壁畫", "秘境"]
  },
  {
    id: 16, city: "米蘭", day: 10,
    name: "聖老楞佐大殿",
    nameEn: "San Lorenzo Maggiore",
    description: "米蘭最古老的教堂之一，建於 4 世紀。前方有 16 根羅馬科林斯柱（來自更早的羅馬神殿），形成壯觀柱廊廣場。內部 4 世紀聖阿奎利諾禮拜堂保有早期基督教馬賽克。",
    address: "Corso di Porta Ticinese, 35, 20123 Milano",
    hours: "週一至五 8:00–18:30；週六日 9:00–19:00",
    suggestedTime: "Day 10 上午路過（✅ 開放）",
    ticket: "免費",
    mustSee: "4 世紀早期基督教教堂、16 根羅馬柱廊",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Milano_-_Basilica_san_Lorenzo_a_porta_Ticinese.jpg/960px-Milano_-_Basilica_san_Lorenzo_a_porta_Ticinese.jpg",
    tags: ["免費", "早期基督教", "羅馬柱廊"]
  },
  {
    id: 17, city: "米蘭", day: 11,
    name: "聖安博羅修大殿",
    nameEn: "Basilica di Sant'Ambrogio",
    description: "米蘭最神聖的教堂，4 世紀由米蘭主保聖人聖安博修建。倫巴底羅馬式建築的原型，內部氛圍極其莊嚴。聖安博與兩位殉道聖人遺骸供奉於主祭壇下地下室。達文西稱此為「真正的米蘭之心」。",
    address: "Piazza Sant'Ambrogio, 15, 20123 Milano",
    hours: "週一至六 7:30–12:00 / 14:30–19:00；週日 7:30–13:00 / 15:00–20:00",
    suggestedTime: "Day 11 上午 11:30（✅ 開放）",
    ticket: "免費",
    mustSee: "4 世紀倫巴底羅馬式建築、地下室聖人遺骸",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/San_Ambrosio_00.jpg/960px-San_Ambrosio_00.jpg",
    tags: ["免費", "倫巴底羅馬式", "主保聖人"]
  }
];
