const restaurants = [
  {
    id: 1, city: "羅馬", day: 1,
    name: "Bar del Gambero",
    nameEn: "",
    cuisine: "早餐 / 咖啡",
    description: "西班牙階梯附近的經典咖啡館，站著喝 Cappuccino 配可頌是義式早餐標準動作。牆上掛滿老照片，氣氛傳統道地，當地人常客居多。",
    address: "Via del Gambero, 30, 00187 Roma",
    hours: "07:00–20:00",
    suggestedTime: "Day 1 早上 9:00 體驗義式早餐",
    price: "€3–5",
    mustEat: "Cappuccino + Cornetto（可頌）",
    rating: "Google 4.3★",
    image: "",
    tags: ["早餐", "咖啡", "當地人"]
  },
  {
    id: 2, city: "羅馬", day: 1,
    name: "La Strega Nocciola",
    nameEn: "",
    cuisine: "Gelato 冰淇淋",
    description: "西班牙階梯區人氣手工 Gelato 店，招牌榛果（Nocciola）和開心果口味濃郁純正。晚上散步後來一杯，幸福感滿滿。",
    address: "Via della Vite, 100, 00187 Roma",
    hours: "11:00–23:00",
    suggestedTime: "Day 1 傍晚 17:30 晚餐前的幸福甜點",
    price: "€3–5",
    mustEat: "榛果（Nocciola）與開心果口味",
    rating: "",
    image: "",
    tags: ["Gelato", "甜點", "散步美食"]
  },
  {
    id: 3, city: "羅馬", day: 1,
    name: "Pastificio Guerra",
    nameEn: "",
    cuisine: "義大利麵（站立式）",
    description: "1918 年創立的站立式義大利麵名店，菜單每天只有兩種現煮新鮮生麵（可選番茄或奶油醬），€5 銅板價在羅馬極罕見。內用座位極少，多數人站著吃，體驗道地羅馬日常。",
    address: "Via della Croce, 8, 00187 Roma",
    hours: "週一至六 10:00–19:30；週日 10:00–16:00",
    suggestedTime: "Day 1 晚餐 18:00（簡單吃，享受羅馬夜晚）",
    price: "約 €5",
    mustEat: "每日現煮新鮮生麵",
    rating: "Google 4.2★ · 1918 年創立 · 🦐 GR 歷史名店",
    image: "",
    tags: ["站立式", "銅板價", "1918", "歷史", "🦐紅蝦"]
  },
  {
    id: 4, city: "羅馬", day: 1,
    name: "Pinsitaly Trevi",
    nameEn: "",
    cuisine: "Pinsa 羅馬式披薩",
    description: "專賣 Pinsa——羅馬式橢圓形輕盈披薩，使用三種麵粉混合發酵，比傳統披薩更輕更好消化。位於許願池旁，備用晚餐好選擇。Google 評分高達 4.8，TripAdvisor 滿分 5/5。",
    address: "Via della Panetteria, 12, 00187 Roma",
    hours: "週一至四 10:30–22:30；週五六日 10:30–23:00",
    suggestedTime: "Day 1 備用晚餐",
    price: "€8–12",
    mustEat: "Pinsa 羅馬式橢圓披薩",
    rating: "Google 4.8★ · TripAdvisor 5/5",
    image: "",
    tags: ["Pinsa", "披薩", "備選"]
  },
  {
    id: 5, city: "羅馬", day: 1,
    name: "Pane e Salame",
    nameEn: "",
    cuisine: "三明治 / 冷盤",
    description: "專賣義大利三明治（Panino）與冷肉起司拼盤，食材新鮮、份量大。室內裝潢掛滿火腿和起司，充滿義大利小餐館氛圍。TripAdvisor 評分 4.8（8,542 則評論）。",
    address: "Via di Santa Maria in Via, 19, 00187 Roma",
    hours: "10:00–20:00",
    suggestedTime: "Day 1 週邊午餐或輕食選擇",
    price: "€€",
    mustEat: "義式冷肉三明治",
    rating: "TripAdvisor 4.8/5",
    image: "",
    tags: ["三明治", "冷肉", "輕食"]
  },
  {
    id: 6, city: "羅馬", day: 1,
    name: "Günther Gelato",
    nameEn: "",
    cuisine: "Gelato 冰淇淋",
    description: "羅馬精品 Gelato 代表店之一，以天然食材和新鮮水果製作，口味細緻不甜膩。靠近西班牙階梯，TripAdvisor 評為羅馬甜點類第 266 名。",
    address: "Via dei Due Macelli, 108, 00187 Roma",
    hours: "10:00–23:00",
    suggestedTime: "Day 1 週邊 Gelato 選擇",
    price: "€",
    mustEat: "季節水果 Gelato",
    rating: "TripAdvisor 4.3/5",
    image: "",
    tags: ["Gelato", "甜點", "天然"]
  },
  {
    id: 7, city: "羅馬", day: 1,
    name: "Trecaffè",
    nameEn: "",
    cuisine: "咖啡 / 輕食",
    description: "位於西班牙階梯附近的經典咖啡館，供應早餐、輕食與咖啡。店內裝潢典雅，適合短暫歇腳補充能量。",
    address: "Via dei Due Macelli, 107, 00187 Roma",
    hours: "07:00–20:00",
    suggestedTime: "Day 1 早餐或輕食備選",
    price: "€€",
    mustEat: "咖啡 + 輕食",
    rating: "",
    image: "",
    tags: ["咖啡", "輕食"]
  },
  {
    id: 8, city: "羅馬", day: 1,
    name: "Ciampini Roma",
    nameEn: "",
    cuisine: "早餐 / 咖啡",
    description: "位於 Piazza San Lorenzo in Lucina 的傳統咖啡館，對面就是美麗的教堂廣場。可在戶外座位享受羅馬早晨的悠閒時光。",
    address: "Piazza di San Lorenzo in Lucina, 29, 00186 Roma",
    hours: "07:00–20:00",
    suggestedTime: "Day 1 早餐備選",
    price: "€€",
    mustEat: "Cappuccino + Cornetto",
    rating: "Google 4.2★",
    image: "",
    tags: ["早餐", "咖啡", "戶外座位"]
  },
  {
    id: 9, city: "羅馬", day: 2,
    name: "L'Antico Forno di Fontana Trevi",
    nameEn: "",
    cuisine: "烘焙 / 披薩",
    description: "羅馬最受歡迎的麵包店之一，隱身在許願池旁的小巷。招牌白披薩（Pizza Bianca）外酥內軟，充滿橄欖油香氣。早上 7 點開門，適合買了邊走邊吃。",
    address: "Via delle Muratte, 90, 00187 Roma",
    hours: "07:00–19:00",
    suggestedTime: "Day 2 早上 8:00 買早餐前往鎖鏈堂",
    price: "€",
    mustEat: "Pizza Bianca（白披薩）",
    rating: "TripAdvisor 4.3/5（946 則評論）",
    image: "",
    tags: ["烘焙", "披薩", "外帶", "早餐"]
  },
  {
    id: 10, city: "羅馬", day: 2,
    name: "Tazza d'Oro（金杯咖啡）",
    nameEn: "La Casa del Caffè Tazza d'Oro",
    cuisine: "咖啡",
    description: "羅馬最具代表性的咖啡店之一，1946 年創立，與萬神殿相對。以自家烘焙的咖啡豆聞名，招牌 Granita al Caffè（咖啡冰沙加鮮奶油）是炎夏必喝。店內也賣咖啡豆，適合當伴手禮。",
    address: "Via degli Orfani, 84, 00186 Roma",
    hours: "07:00–19:00",
    suggestedTime: "Day 2 下午 16:30 萬神殿旁",
    price: "€3–5",
    mustEat: "Granita al Caffè（咖啡冰沙）",
    rating: "Google 4.5★ · TripAdvisor 4.5/5（3,028 則評論）",
    image: "",
    tags: ["咖啡", "1946", "萬神殿", "伴手禮"]
  },
  {
    id: 11, city: "羅馬", day: 2,
    name: "Pizza Florida",
    nameEn: "",
    cuisine: "披薩",
    description: "羅馬老城區的平價披薩店，鄰近萬神殿與鮮花廣場。提供秤重披薩（Pizza al taglio），口味多樣，是快速午餐的好選擇。",
    address: "Via Florida, 25, 00186 Roma",
    hours: "10:00–22:00",
    suggestedTime: "Day 2 快速午餐備選",
    price: "€",
    mustEat: "Pizza al taglio（秤重披薩）",
    rating: "Google 4.8★",
    image: "",
    tags: ["披薩", "平價", "快速"]
  },
  {
    id: 12, city: "羅馬", day: 2,
    name: "Alice Pizza",
    nameEn: "",
    cuisine: "披薩",
    description: "羅馬知名的 Pizza al taglio 連鎖店，位於 Corso Vittorio Emanuele II。主打方形秤重披薩，口味豐富多樣，從經典瑪格麗特到松露口味都有。",
    address: "Corso Vittorio Emanuele II, 35, 00186 Roma",
    hours: "07:00–22:00",
    suggestedTime: "Day 2 快速午餐備選",
    price: "€",
    mustEat: "秤重披薩",
    rating: "Google 4.3★",
    image: "",
    tags: ["披薩", "平價", "連鎖"]
  },
  {
    id: 13, city: "羅馬", day: 2,
    name: "Da Enzo al 29",
    nameEn: "",
    cuisine: "羅馬傳統料理",
    description: "越河區（Trastevere）最難排到的羅馬傳統餐廳之一，獲米其林 Bib Gourmand 肯定。主打 Carbonara、Cacio e Pepe 等經典羅馬麵，不接受預約需現場排隊 30–60 分鐘。",
    address: "Via dei Vascellari, 29, 00153 Roma",
    hours: "12:30–15:00 / 18:30–22:30（週日公休）",
    suggestedTime: "Day 2 晚餐（⚠️ 週日公休，提前排隊）",
    price: "€12–18",
    mustEat: "Carbonara · Cacio e Pepe",
    rating: "Google 4.3★（5,427 則評論）· 🦐 Michelin Bib Gourmand",
    image: "",
    tags: ["羅馬經典", "米其林", "排隊名店", "❌ 週日休", "🦐紅蝦"]
  },
  {
    id: 14, city: "羅馬", day: 2,
    name: "Venchi",
    nameEn: "",
    cuisine: "巧克力 / Gelato",
    description: "義大利頂級巧克力品牌，1878 年創立於都靈。萬神殿旁的旗艦店供應各式手工巧克力、Gelato 與巧克力飲品，是晚餐後的完美句點。",
    address: "Piazza della Rotonda, 6, 00186 Roma",
    hours: "10:00–21:00",
    suggestedTime: "Day 2 萬神殿旁甜點",
    price: "€",
    mustEat: "巧克力 Gelato · 手工巧克力",
    rating: "1878 年創立",
    image: "",
    tags: ["巧克力", "Gelato", "1878", "伴手禮"]
  },
  {
    id: 15, city: "羅馬", day: 3,
    name: "Pergamino Caffè",
    nameEn: "",
    cuisine: "咖啡 / 早餐",
    description: "梵蒂岡聖彼得廣場附近的咖啡館，早晨提供簡單早餐與咖啡，位置方便前往聖彼得大教堂。適合早上出發前快速補充能量。",
    address: "Piazza del Risorgimento, 7, 00192 Roma",
    hours: "07:00–19:00",
    suggestedTime: "Day 3 早上 7:30 早餐後前往梵蒂岡",
    price: "€€",
    mustEat: "Cappuccino + Cornetto",
    rating: "",
    image: "",
    tags: ["早餐", "咖啡", "梵蒂岡"]
  },
  {
    id: 16, city: "羅馬", day: 3,
    name: "Pizza Zizza",
    nameEn: "",
    cuisine: "披薩",
    description: "梵蒂岡附近的秤重披薩店，價格平實、口味選擇多。適合參觀完聖彼得大教堂後快速解決午餐。",
    address: "Via delle Fornaci, 11, 00165 Roma",
    hours: "09:00–22:00",
    suggestedTime: "Day 3 梵蒂岡附近午餐",
    price: "€",
    mustEat: "秤重披薩",
    rating: "Google 4.5★",
    image: "",
    tags: ["披薩", "平價", "梵蒂岡"]
  },
  {
    id: 17, city: "羅馬", day: 3,
    name: "Bar Farnese",
    nameEn: "",
    cuisine: "咖啡 / 輕食",
    description: "位於優美的法爾內塞廣場（Piazza Farnese），是當地人喜愛的街角咖啡館。適合從鮮花廣場散步過來時歇腳喝杯咖啡。",
    address: "Piazza Farnese, 2, 00186 Roma",
    hours: "08:00–20:00",
    suggestedTime: "Day 3 下午散步歇腳",
    price: "€",
    mustEat: "Espresso",
    rating: "",
    image: "",
    tags: ["咖啡", "當地人", "廣場"]
  },
  {
    id: 18, city: "羅馬", day: 3,
    name: "Forno Campo de' Fiori",
    nameEn: "",
    cuisine: "烘焙 / 披薩",
    description: "鮮花廣場的傳奇麵包店，每天早上出爐的 Pizza Bianca 是羅馬人的最愛。下午 2 點就打烊——想吃要趁早！在地人排隊買了就走，配上一杯咖啡就是完美早餐。",
    address: "Campo de' Fiori, 00186 Roma",
    hours: "07:00–14:00（下午打烊！）",
    suggestedTime: "Day 3 早上 10:00 鮮花廣場早午餐",
    price: "€",
    mustEat: "Pizza Bianca（白披薩）",
    rating: "Google 4.5★ · Yelp 4.5/5（200 則評論）",
    image: "",
    tags: ["烘焙", "披薩", "百年老店", "早鳥限定"]
  },
  {
    id: 19, city: "羅馬", day: 3,
    name: "Da Fortunata",
    nameEn: "",
    cuisine: "羅馬傳統料理",
    description: "以手工現拉義大利麵聞名的羅馬餐館，廚房透明可見師傅現場拉製麵條。Carbonara 和 Cacio e Pepe 經典道地，Google 評分 4.4 星，評論數近 3 萬則。",
    address: "Via del Pellegrino, 11, 00186 Roma",
    hours: "12:00–15:00 / 18:00–22:30",
    suggestedTime: "Day 3 晚餐（鮮花廣場步行 3 分鐘）",
    price: "€€",
    mustEat: "手工現拉 Carbonara",
    rating: "Google 4.4★（29,278 則評論）",
    image: "",
    tags: ["手工麵", "羅馬經典", "人氣名店"]
  },
  {
    id: 20, city: "羅馬", day: 3,
    name: "Bonci Pizzarium",
    nameEn: "",
    cuisine: "披薩（秤重）",
    description: "羅馬披薩之神 Gabriele Bonci 的旗艦店，被譽為「世界最佳披薩 al taglio」。Gambero Rosso 評鑑 Tre Rotelle（最高分 96/100）。麵團使用天然酵母發酵 24–36 小時，配料創意十足。",
    address: "Via della Meloria, 43, 00192 Roma",
    hours: "10:00–23:00",
    suggestedTime: "Day 3 梵蒂岡附近午餐（步行 10 分鐘）",
    price: "€5–10",
    mustEat: "Pizza al taglio 秤重披薩（每週更換口味）",
    rating: "Google 4.0★ · 🦐 GR Tre Rotelle（96 分）",
    image: "",
    tags: ["披薩", "評鑑最高分", "排隊名店", "🦐紅蝦"]
  },
  {
    id: 21, city: "羅馬", day: 3,
    name: "Old Bridge Gelateria",
    nameEn: "",
    cuisine: "Gelato 冰淇淋",
    description: "梵蒂岡城牆外的老牌 Gelato 店，價格實惠、份量大，是參觀完博物館後消暑解渴的首選。雖然稱不上最頂級，但 CP 值超高。",
    address: "Viale dei Bastioni di Michelangelo, 5, 00192 Roma",
    hours: "10:00–22:00",
    suggestedTime: "Day 3 梵蒂岡博物館後",
    price: "€3–5",
    mustEat: "各式口味 Gelato",
    rating: "",
    image: "",
    tags: ["Gelato", "梵蒂岡", "CP值高"]
  },
  {
    id: 22, city: "羅馬", day: 4,
    name: "Mercato Centrale Roma",
    nameEn: "",
    cuisine: "美食廣場",
    description: "羅馬 Termini 車站旁的大型美食廣場，共有三層樓多個攤位。出發前可在這裡快速解決早餐或買些車上點心。Trapizzino、Bonci Panarium 等高品質攤位都在此設點。",
    address: "Via Giolitti, 36, 00185 Roma",
    hours: "08:00–22:00",
    suggestedTime: "Day 4 早上 8:00 出發前早餐",
    price: "€€",
    mustEat: "Trapizzino（三角口袋披薩）",
    rating: "",
    image: "",
    tags: ["美食廣場", "Termini", "出發前"]
  },
  {
    id: 23, city: "羅馬", day: 4,
    name: "Trapizzino",
    nameEn: "",
    cuisine: "街頭美食（三角口袋披薩）",
    description: "創新羅馬街頭美食——Trapizzino 是 Pizza Bianca 折成三角形口袋，填入傳統燉煮內餡（如牛尾、雞肝等）。位於 Mercato Centrale Roma 內，出發前可帶走當車上點心。",
    address: "Mercato Centrale Roma 內",
    hours: "08:00–21:00",
    suggestedTime: "Day 4 早上 Mercato Centrale 早餐",
    price: "€",
    mustEat: "Trapizzino 三角披薩口袋",
    rating: "",
    image: "",
    tags: ["街頭美食", "創新", "外帶"]
  },
  {
    id: 24, city: "羅馬", day: 4,
    name: "Bonci (Panarium)",
    nameEn: "",
    cuisine: "披薩",
    description: "Bonci 在 Mercato Centrale Roma 內的分店，同樣供應高品質 Pizza al taglio。如果沒時間去 Pizzarium 本店，這裡是方便的替代選擇。",
    address: "Mercato Centrale Roma 內",
    hours: "08:00–21:00",
    suggestedTime: "Day 4 Mercato Centrale 早餐",
    price: "€",
    mustEat: "Pizza al taglio",
    rating: "Bonci 體系 · Tre Rotelle 96 分",
    image: "",
    tags: ["披薩", "Bonci", "美食廣場"]
  },
  {
    id: 25, city: "羅馬", day: 4,
    name: "VyTA",
    nameEn: "",
    cuisine: "咖啡 / 輕食",
    description: "位於 Roma Termini 車站內的時尚咖啡吧，供應精品咖啡、輕食與甜點。等車時可以外帶一杯咖啡上車。",
    address: "Roma Termini 車站內",
    hours: "06:00–23:00",
    suggestedTime: "Day 4 在 Termini 等車時",
    price: "€€",
    mustEat: "精品咖啡",
    rating: "",
    image: "",
    tags: ["咖啡", "車站", "輕食"]
  },
  {
    id: 26, city: "佛羅倫斯", day: 4,
    name: "Trattoria Zà Zà",
    nameEn: "",
    cuisine: "托斯卡納傳統料理",
    description: "佛羅倫斯最具代表性的 trattoria 之一，位於中央市場旁。以佛羅倫斯丁骨牛排（Bistecca alla Fiorentina）聞名，份量超大。室內裝潢色彩繽紛，氣氛熱鬧。Google 評分 4.5，TripAdvisor 4.3（16,641 則評論）。",
    address: "Piazza del Mercato Centrale, 26r, 50123 Firenze",
    hours: "11:00–23:00（每天營業）",
    suggestedTime: "Day 4 晚餐 19:30（建議提前預約）",
    price: "€25–35",
    mustEat: "Bistecca alla Fiorentina（佛羅倫斯牛排）",
    rating: "Google 4.5★ · TripAdvisor 4.3/5",
    image: "",
    tags: ["丁骨牛排", "托斯卡納", "排隊名店", "佛羅倫斯必吃"]
  },
  {
    id: 27, city: "佛羅倫斯", day: 4,
    name: "Trattoria Dall'Oste",
    nameEn: "",
    cuisine: "托斯卡納 / 牛排",
    description: "佛羅倫斯車站旁的牛排專門店，Google 評分 4.6 星。以乾式熟成丁骨牛排著稱，價格較 Zà Zà 更高檔但品質也更精緻。另有套餐選擇。",
    address: "Via Luigi Alamanni, 3r, 50123 Firenze",
    hours: "11:00–23:00",
    suggestedTime: "Day 4 晚餐備選（車站步行 5 分鐘）",
    price: "€€€",
    mustEat: "乾式熟成丁骨牛排",
    rating: "Google 4.6★",
    image: "",
    tags: ["牛排", "高檔", "乾式熟成"]
  },
  {
    id: 28, city: "佛羅倫斯", day: 4,
    name: "Gilli",
    nameEn: "",
    cuisine: "咖啡 / 歷史咖啡館",
    description: "佛羅倫斯最古老的咖啡館之一，1733 年創立，位於共和國廣場（Piazza della Repubblica）。內部保留新藝術風格裝潢，是文人雅士的聚會場所。早餐到宵夜都營業。",
    address: "Piazza della Repubblica, 50123 Firenze",
    hours: "07:00–02:00",
    suggestedTime: "Day 4 早上 11:00 抵達佛羅倫斯後",
    price: "€€",
    mustEat: "經典義式早餐 · 甜點",
    rating: "1733 年創立 · TripAdvisor 4.8/5",
    image: "",
    tags: ["歷史咖啡館", "1733", "共和國廣場", "新藝術風格"]
  },
  {
    id: 29, city: "佛羅倫斯", day: 4,
    name: "Mercato Centrale Firenze",
    nameEn: "",
    cuisine: "美食廣場 / 市場",
    description: "佛羅倫斯中央市場，一樓為傳統生鮮市場，二樓為美食廣場（營業至午夜）。Nerbone 的牛肚包是一樓排隊名店，二樓則有多樣化的托斯卡納美食攤位。",
    address: "Via dell'Ariento, 50123 Firenze",
    hours: "一樓 07:00–15:00；二樓 10:00–00:00",
    suggestedTime: "Day 4 午餐 12:45 品嚐牛肚包",
    price: "€8–15",
    mustEat: "Nerbone 牛肚包（Panino con Lampredotto）",
    rating: "",
    image: "",
    tags: ["市場", "牛肚包", "美食廣場", "家庭友善"]
  },
  {
    id: 30, city: "佛羅倫斯", day: 5,
    name: "All'Antico Vinaio",
    nameEn: "",
    cuisine: "三明治（Schiacciata）",
    description: "世界最知名的義大利三明治店，被 50 Top Italy 評為 #39！Schiacciata（托斯卡納扁平麵包）夾入新鮮食材，份量巨大、口味完美。排隊 20–30 分鐘是常態，但絕對值得。TripAdvisor 超過 4 萬則評論，評分居高不下。",
    address: "Via dei Neri, 65r, 50122 Firenze",
    hours: "10:00–22:00（每天營業）",
    suggestedTime: "Day 5 午餐 12:00（排隊約 20–30 分）",
    price: "€8–12",
    mustEat: "Schiacciata 義大利三明治（推薦 Inferno 口味）",
    rating: "Google 4.5★（40,735 則評論）· 🦐 GR 專文推薦",
    image: "",
    tags: ["三明治", "排隊名店", "傳奇", "Schiacciata", "🦐紅蝦"]
  },
  {
    id: 31, city: "佛羅倫斯", day: 5,
    name: "Gelateria dei Neri",
    nameEn: "",
    cuisine: "Gelato 冰淇淋",
    description: "佛羅倫斯最佳手工 Gelato 之一，使用天然食材、無人工添加物。位於 Via dei Neri（與 All'Antico Vinaio 同一條街），排完三明治再來杯 Gelato 是完美搭配。",
    address: "Via dei Neri, 20r, 50122 Firenze",
    hours: "11:00–22:00",
    suggestedTime: "Day 5 三明治後 Gelato 收尾",
    price: "€3–5",
    mustEat: "各式手工 Gelato（推薦開心果）",
    rating: "",
    image: "",
    tags: ["Gelato", "天然", "手工"]
  },
  {
    id: 32, city: "佛羅倫斯", day: 5,
    name: "Ben Caffè",
    nameEn: "",
    cuisine: "早餐 / 咖啡",
    description: "佛羅倫斯優質早餐選擇，靠近百花大教堂。供應精品咖啡、可頌與輕食。Google 評分 4.7，氣氛悠閒，是爬圓頂前補充能量的好去處。",
    address: "Via delle Oche, 7, 50122 Firenze",
    hours: "07:30–18:00",
    suggestedTime: "Day 5 早上 8:00 烏菲茲前早餐",
    price: "€€",
    mustEat: "Cappuccino + 可頌",
    rating: "Google 4.7★",
    image: "",
    tags: ["早餐", "咖啡", "百花大教堂"]
  },
  {
    id: 33, city: "佛羅倫斯", day: 5,
    name: "Ditta Artigianale",
    nameEn: "",
    cuisine: "精品咖啡",
    description: "佛羅倫斯第三波咖啡浪潮的先驅，2013 年創立。自家烘焙咖啡豆，提供手沖、拉花、冷萃等多種沖煮方式。空間設計現代，適合文青風格歇腳。",
    address: "Via dei Neri, 32r, 50122 Firenze",
    hours: "07:30–19:00",
    suggestedTime: "Day 5 下午咖啡時光（老橋旁）",
    price: "€€",
    mustEat: "手沖精品咖啡",
    rating: "Google 4.3★ · 2013 年創立",
    image: "",
    tags: ["精品咖啡", "文青", "第三波"]
  },
  {
    id: 34, city: "佛羅倫斯", day: 5,
    name: "Rivoire",
    nameEn: "",
    cuisine: "歷史咖啡館 / 甜點",
    description: "1872 年創立的傳奇咖啡館，位於領主廣場（Piazza della Signoria），正對舊宮。以手工巧克力和熱巧克力聞名，是佛羅倫斯上流社會的聚會場所。價位偏高但體驗無價。",
    address: "Piazza della Signoria, 50122 Firenze",
    hours: "07:30–01:00",
    suggestedTime: "Day 5 下午在領主廣場歇腳",
    price: "€€€",
    mustEat: "熱巧克力 · 手工巧克力",
    rating: "1872 年創立 · Google 4.5★",
    image: "",
    tags: ["歷史咖啡館", "1872", "領主廣場", "巧克力"]
  },
  {
    id: 35, city: "佛羅倫斯", day: 6,
    name: "Mercato Centrale Firenze 二樓",
    nameEn: "",
    cuisine: "美食廣場",
    description: "中央市場二樓美食廣場，營業至午夜！從比薩回來後可在此解決晚餐。Il Tartufo（松露專賣）、La Pizzeria 等多個攤位選擇，適合家庭——每個人選自己喜歡的。",
    address: "Mercato Centrale, 二樓, 50123 Firenze",
    hours: "10:00–00:00",
    suggestedTime: "Day 6 下午 14:00 從比薩回來後",
    price: "€8–15",
    mustEat: "Il Tartufo 松露義大利麵",
    rating: "",
    image: "",
    tags: ["美食廣場", "市場", "家庭友善", "深夜"]
  },
  {
    id: 36, city: "佛羅倫斯", day: 6,
    name: "Il Tartufo",
    nameEn: "",
    cuisine: "松露專賣",
    description: "位於中央市場二樓的松露專賣攤位，提供新鮮松露刨片在各式菜餚上。松露義大利麵、燉飯是招牌，香氣撲鼻。想吃松露又不想花大錢的好選擇。",
    address: "Mercato Centrale 二樓, Firenze",
    hours: "10:00–22:00",
    suggestedTime: "Day 6 中央市場午餐或晚餐",
    price: "€€",
    mustEat: "松露義大利麵",
    rating: "",
    image: "",
    tags: ["松露", "市場", "平價奢華"]
  },
  {
    id: 37, city: "佛羅倫斯", day: 6,
    name: "Yellow Bar",
    nameEn: "",
    cuisine: "義式料理",
    description: "佛羅倫斯學院美術館附近的傳統餐館，提供經典托斯卡納料理。招牌黃色店面非常醒目。",
    address: "Via del Proconsolo, 39r, 50122 Firenze",
    hours: "12:00–15:00 / 18:45–23:00（週一公休）",
    suggestedTime: "Day 6 備選晚餐（⚠️ 週一公休）",
    price: "€€",
    mustEat: "托斯卡納料理",
    rating: "Google 4.4★ · ❌ 週一公休",
    image: "",
    tags: ["托斯卡納", "備選", "❌ 週一休"]
  },
  {
    id: 38, city: "佛羅倫斯", day: 6,
    name: "La Prosciutteria",
    nameEn: "",
    cuisine: "火腿拼盤 / 輕食",
    description: "專賣義大利冷肉與起司拼盤的小店，位於 Via dei Neri。點一份混合拼盤搭配紅酒或啤酒，就是最道地的義式晚餐。氣氛輕鬆，適合 Casual 用餐。",
    address: "Via dei Neri, 54r, 50122 Firenze",
    hours: "11:00–22:00",
    suggestedTime: "Day 6 晚餐備選（步行可達）",
    price: "€10–18",
    mustEat: "托斯卡納火腿拼盤",
    rating: "",
    image: "",
    tags: ["冷肉", "拼盤", "輕食", "紅酒"]
  },
  {
    id: 39, city: "威尼斯", day: 7,
    name: "Rosa Salva",
    nameEn: "",
    cuisine: "烘焙 / 咖啡",
    description: "威尼斯老字號烘焙咖啡館，在聖馬可廣場附近有多家分店。供應傳統威尼斯甜點與咖啡，是早餐或午後點心的好選擇。TripAdvisor 評分不俗。",
    address: "Piazza San Marco, 87, 30124 Venezia",
    hours: "08:00–20:00",
    suggestedTime: "Day 7 早上抵達威尼斯後早餐",
    price: "€€",
    mustEat: "威尼斯傳統甜點 · Cappuccino",
    rating: "Google 4.3★",
    image: "",
    tags: ["烘焙", "咖啡", "聖馬可"]
  },
  {
    id: 40, city: "威尼斯", day: 7,
    name: "Osteria da Mariano",
    nameEn: "",
    cuisine: "威尼斯料理",
    description: "位於威尼斯本島對岸 Mestre 的傳統威尼斯餐館，是離開本島路過 Mestre 時的用餐選擇。TripAdvisor 評分 4.2/5。",
    address: "Corso del Popolo, 201, Mestre",
    hours: "12:00–15:00 / 19:00–22:30",
    suggestedTime: "Day 7–8 Mestre 路過用餐",
    price: "€€",
    mustEat: "威尼斯海鮮料理",
    rating: "TripAdvisor 4.2/5（287 則評論）",
    image: "",
    tags: ["Mestre", "海鮮", "晚餐"]
  },
  {
    id: 41, city: "威尼斯", day: 7,
    name: "Caffè Florian",
    nameEn: "",
    cuisine: "歷史咖啡館",
    description: "1720 年創立、全世界最古老的咖啡館之一！位於聖馬可廣場，是威尼斯最具代表性的地標咖啡館。金碧輝煌的內部裝潢、現場樂團演奏，是體驗威尼斯貴族風華的必訪之地。🦐 Gambero Rosso 2 Chicchi 評鑑。",
    address: "Piazza San Marco, 57, 30124 Venezia",
    hours: "09:00–01:00（每天）",
    suggestedTime: "Day 7 下午 14:00 聖馬可廣場體驗百年風華",
    price: "€10–15（座位費另計）",
    mustEat: "威尼斯式咖啡 · 熱巧克力",
    rating: "1720 年創立 · 🦐 GR 2 Chicchi",
    image: "",
    tags: ["歷史咖啡館", "1720", "聖馬可廣場", "樂團", "🦐紅蝦"]
  },
  {
    id: 42, city: "威尼斯", day: 7,
    name: "Trattoria Al Gazzettino",
    nameEn: "",
    cuisine: "威尼斯海鮮",
    description: "聖馬可廣場附近的人氣海鮮餐廳，以墨魚麵（Spaghetti al Nero di Seppia）聞名。座位有限，建議提前預約。",
    address: "San Marco, 376, 30124 Venezia",
    hours: "12:00–15:00 / 18:00–22:00",
    suggestedTime: "Day 7 晚餐",
    price: "€15–25",
    mustEat: "墨魚麵（Spaghetti al Nero di Seppia）",
    rating: "",
    image: "",
    tags: ["海鮮", "墨魚麵", "威尼斯"]
  },
  {
    id: 43, city: "威尼斯", day: 8,
    name: "Caffè del Doge",
    nameEn: "",
    cuisine: "咖啡 / 輕食",
    description: "威尼斯自家烘焙咖啡品牌（總部位於 Mestre），供應高品質義式咖啡。在威尼斯本島有多家分店，是早晨咖啡的好去處。Google 評分 4.4，TripAdvisor 4.4（826 則評論）。",
    address: "Calle dei Cinque, 609, 30124 Venezia",
    hours: "07:00–18:30",
    suggestedTime: "Day 8 早上 7:30 早餐後出發彩色島",
    price: "€€",
    mustEat: "Cappuccino · 自家烘焙咖啡豆",
    rating: "Google 4.4★ · TripAdvisor 4.4/5",
    image: "",
    tags: ["咖啡", "烘豆", "威尼斯"]
  },
  {
    id: 44, city: "威尼斯", day: 8,
    name: "Trattoria da Romano",
    nameEn: "",
    cuisine: "威尼斯海鮮（Burano）",
    description: "彩色島 Burano 最具傳奇色彩的餐廳，🦐 Gambero Rosso 推薦！以 Risotto di Gò（蝦虎魚燉飯）聞名，是前往 Burano 不可錯過的美食體驗。建議提前預約。",
    address: "Via Galuppi, 221, Burano",
    hours: "12:00–15:00 / 19:00–22:30",
    suggestedTime: "Day 8 中午 Burano 午餐",
    price: "€25–40",
    mustEat: "Risotto di Gò（蝦虎魚燉飯）",
    rating: "Google 4.2★ · 🦐 GR 推薦威尼斯 TOP 10",
    image: "",
    tags: ["Burano", "海鮮", "燉飯", "歷史名店", "🦐紅蝦"]
  },
  {
    id: 45, city: "威尼斯", day: 8,
    name: "Osteria alle Testiere",
    nameEn: "",
    cuisine: "威尼斯海鮮（高級）",
    description: "威尼斯最難預約的海鮮餐廳之一，僅 22 個座位。OAD 評選歐洲 Top 87 餐廳，獲 Michelin Plate 推薦。每日菜單由漁獲決定，食材新鮮度無可挑剔。需提前 3–4 週線上預約。",
    address: "Calle del Mondo Novo, 5801, 30124 Venezia",
    hours: "12:00–15:00 / 19:00–22:30（週日一公休）",
    suggestedTime: "Day 8 晚餐（需提前預約）",
    price: "€€€",
    mustEat: "威尼斯式海鮮拼盤（每日漁獲定）",
    rating: "Google 4.9★ · Michelin Plate · OAD #87 🦐",
    image: "",
    tags: ["海鮮", "米其林", "難預約", "❌ 週日一休", "🦐紅蝦"]
  },
  {
    id: 46, city: "威尼斯", day: 8,
    name: "Fritto Misto",
    nameEn: "",
    cuisine: "炸海鮮（街頭）",
    description: "彩色島 Burano 下船處附近的炸海鮮小吃，用紙袋裝著現炸的蝦、小魚、花枝等，灑上檸檬汁邊走邊吃，是最有度假感的 Burano 體驗。",
    address: "Burano 下船處附近",
    hours: "10:00–19:00",
    suggestedTime: "Day 8 Burano 散步小吃",
    price: "€",
    mustEat: "現炸海鮮綜合",
    rating: "",
    image: "",
    tags: ["Burano", "炸海鮮", "街頭", "散步美食"]
  },
  {
    id: 47, city: "威尼斯", day: 8,
    name: "Pizzeria da Pino",
    nameEn: "",
    cuisine: "披薩（Mestre）",
    description: "Mestre 的老牌披薩店，供應傳統圓盤披薩。如果從威尼斯本島搭火車回 Mestre 住宿，是方便的晚餐選擇。",
    address: "Piazzale Luigi Candiani, 17, Mestre",
    hours: "12:00–14:30 / 18:30–23:00",
    suggestedTime: "Day 8 Mestre 住宿晚餐備選",
    price: "€€",
    mustEat: "傳統圓盤披薩",
    rating: "",
    image: "",
    tags: ["披薩", "Mestre", "晚餐"]
  },
  {
    id: 48, city: "米蘭", day: 9,
    name: "Orsonero Coffee",
    nameEn: "",
    cuisine: "精品咖啡",
    description: "米蘭第三波咖啡浪潮的代表，2016 年創立。店內空間極簡小巧，但咖啡品質是米蘭頂尖。自家選豆、手沖與拉花都極講究。",
    address: "Via Giuseppe Broggi, 15, 20129 Milano",
    hours: "週一至五 08:00–17:00（⚠️ 週六日公休）",
    suggestedTime: "Day 9 早上咖啡（❌ 週六日休，Day 9 為週四 ✅）",
    price: "€€",
    mustEat: "手沖精品咖啡",
    rating: "2016 年創立 · Google 4.7★",
    image: "",
    tags: ["精品咖啡", "第三波", "2016"]
  },
  {
    id: 49, city: "米蘭", day: 9,
    name: "Starbucks Reserve Roastery",
    nameEn: "",
    cuisine: "咖啡 / 體驗",
    description: "全球僅六家的星巴克臻選烘焙工坊，米蘭店位於科爾杜西奧廣場（Piazza Cordusio）附近的前郵政總局大樓。三層樓的沉浸式咖啡體驗空間，有烘焙區、調酒吧與限定飲品。",
    address: "Piazza Cordusio 附近, 20123 Milano",
    hours: "08:00–23:00",
    suggestedTime: "Day 9 下午 14:30 避暑歇腳",
    price: "€€€",
    mustEat: "限定版咖啡調酒 · 咖啡體驗",
    rating: "",
    image: "",
    tags: ["咖啡", "打卡", "旗艦", "體驗"]
  },
  {
    id: 50, city: "米蘭", day: 9,
    name: "Osteria del Gambero Rosso",
    nameEn: "",
    cuisine: "米蘭傳統料理",
    description: "1983 年創立的米蘭老字號餐廳，名字中有「紅蝦」但與 Gambero Rosso 評鑑無直接關係。主打米蘭經典料理如 Cotoletta alla Milanese 與 Risotto alla Milanese。",
    address: "Viale Pasubio, 8, 20154 Milano",
    hours: "12:00–15:00 / 19:00–00:00（每天）",
    suggestedTime: "Day 9 晚餐",
    price: "€€€",
    mustEat: "Cotoletta alla Milanese（米蘭炸肉排）",
    rating: "1983 年創立 · Google 4.7★",
    image: "",
    tags: ["米蘭經典", "1983", "傳統"]
  },
  {
    id: 51, city: "米蘭", day: 9,
    name: "Luini",
    nameEn: "",
    cuisine: "Panzerotti 炸餃",
    description: "米蘭排隊最誇張的街頭美食傳奇！1949 年創立，專賣 Panzerotti（義大利炸餃），外皮酥脆、內餡香濃（起司、番茄、火腿等）。1949 年至今只賣這一味，€4 起銅板價。",
    address: "Via Santa Radegonda, 16, 20121 Milano",
    hours: "10:00–20:00（週日公休）",
    suggestedTime: "Day 9 午餐 12:00（排隊名店，建議避開尖峰）",
    price: "€4–6",
    mustEat: "Panzerotti 經典起司番茄餡",
    rating: "1949 年創立 · Google 4.5★ · 傳奇排隊名店",
    image: "",
    tags: ["街頭美食", "1949", "排隊名店", "Panzerotti"]
  },
  {
    id: 52, city: "米蘭", day: 10,
    name: "Pizzeria Spontini",
    nameEn: "",
    cuisine: "披薩（厚片米蘭式）",
    description: "1953 年創立的米蘭傳奇披薩店，以厚片、鬆軟、料多的米蘭式披薩聞名。麵團使用高比例橄欖油，口感介於披薩與佛卡夏之間。與拿坡里薄皮完全不同風格。",
    address: "Via Santa Radegonda, 11, 20121 Milano",
    hours: "12:00–15:00 / 18:30–23:00（每天）",
    suggestedTime: "Day 10 快速午餐（大教堂旁）",
    price: "€6–10",
    mustEat: "Margherita 厚片披薩",
    rating: "1953 年創立 · Google 4.2★ · TripAdvisor 3.7/5",
    image: "",
    tags: ["披薩", "1953", "厚片", "米蘭式"]
  },
  {
    id: 53, city: "米蘭", day: 10,
    name: "Piz",
    nameEn: "",
    cuisine: "新派披薩",
    description: "米蘭布雷拉區的新派披薩店，使用高品質食材與長時間發酵的酸種麵團。口味創新且精緻，評為米蘭第 41 名餐廳。Google 評分 4.6。",
    address: "Via Pasquale Sottocorno, 5, 20129 Milano",
    hours: "11:00–15:00 / 18:00–22:30",
    suggestedTime: "Day 10 午餐（布雷拉區）",
    price: "€12–18",
    mustEat: "Risotto alla Milanese（米蘭燉飯）",
    rating: "Google 4.6★ · Milan #41",
    image: "",
    tags: ["披薩", "布雷拉", "新派", "精品"]
  },
  {
    id: 54, city: "米蘭", day: 10,
    name: "Cioccolatitaliani",
    nameEn: "",
    cuisine: "巧克力 / Gelato",
    description: "義大利精品巧克力+Gelato 連鎖店，米蘭大教堂旁的分店位置極佳。供應手工巧克力、濃郁熱巧克力與各式 Gelato，是觀光區的品質保證。",
    address: "Via San Raffaele, 6, 20121 Milano",
    hours: "10:00–22:00",
    suggestedTime: "Day 10 下午甜點或飯後",
    price: "€4–8",
    mustEat: "手工巧克力 · Gelato",
    rating: "",
    image: "",
    tags: ["巧克力", "Gelato", "大教堂"]
  },
  {
    id: 55, city: "米蘭", day: 11,
    name: "Panzerotti Luini",
    nameEn: "",
    cuisine: "Panzerotti 炸餃",
    description: "1949 年創立的傳奇街頭小吃，專賣 Panzerotti（義大利炸餃/烤餃）。外皮薄脆、內餡爆漿，€4 起就能吃到米蘭最經典的平民美食。排隊人龍終年不斷，但前進速度很快。",
    address: "Via Santa Radegonda, 16, 20121 Milano",
    hours: "10:00–20:00（週日公休）",
    suggestedTime: "Day 11 從城堡散步過來當午餐（❌ 週日休）",
    price: "€4–6",
    mustEat: "經典起司番茄 Panzerotti · 甜口味 Nutella",
    rating: "1949 年創立 · Google 4.5★ · TripAdvisor 4.3/5",
    image: "",
    tags: ["街頭美食", "1949", "排隊名店", "Panzerotti"]
  },
  {
    id: 56, city: "米蘭", day: 11,
    name: "Pizzium",
    nameEn: "",
    cuisine: "披薩（義大利各地風格）",
    description: "米蘭新興披薩連鎖品牌，特色是集結義大利不同地區的披薩風格——從拿坡里軟邊到羅馬薄脆都有。Google 評分 4.5。",
    address: "Via Andrea Doria, 17, 20124 Milano",
    hours: "12:00–15:00 / 18:00–23:00",
    suggestedTime: "Day 11 午餐（中央車站附近）",
    price: "€€",
    mustEat: "各地特色披薩",
    rating: "Google 4.5★",
    image: "",
    tags: ["披薩", "連鎖", "各地風格"]
  },
  {
    id: 57, city: "米蘭", day: 11,
    name: "Ratanà",
    nameEn: "",
    cuisine: "米蘭高級料理",
    description: "獲 Gambero Rosso 與 Michelin Guide 雙重推薦的米蘭頂級餐廳，以 Risotto alla Milanese 聞名——被譽為米蘭最佳燉飯。位於 Bosco Verticale（垂直森林）旁，環境現代高雅。",
    address: "Via Gaetano de Castillia, 28, 20124 Milano",
    hours: "12:00–15:00 / 19:00–23:00",
    suggestedTime: "Day 11 告別晚餐（建議預約）",
    price: "約 €80/人",
    mustEat: "Risotto alla Milanese（米蘭燉飯）",
    rating: "Google 4.5★ · 🦐 GR + Michelin Guide",
    image: "",
    tags: ["米其林", "燉飯", "高級", "垂直森林", "🦐紅蝦"]
  },
  {
    id: 58, city: "米蘭", day: 11,
    name: "Pavé",
    nameEn: "",
    cuisine: "烘焙 / 咖啡 / Gelato",
    description: "米蘭最受歡迎的烘焙咖啡館之一，早上是完美的早餐店、下午是咖啡廳、同時供應獲 Gambero Rosso 3 Coni 評鑑的頂級 Gelato。裝潢文青簡約，可頌與甜點品質一流。",
    address: "Via Felice Casati, 27, 20124 Milano",
    hours: "07:30–19:30",
    suggestedTime: "Day 11 早餐或下午茶",
    price: "€5–10",
    mustEat: "可頌 · 咖啡 · Gelato（GR 3 Coni）",
    rating: "Google 4.6★ · 🦐 GR 3 Coni + 最佳 Bar",
    image: "",
    tags: ["烘焙", "咖啡", "Gelato", "文青", "🦐紅蝦"]
  },
  {
    id: 59, city: "米蘭", day: 12,
    name: "Pan Brioche",
    nameEn: "",
    cuisine: "機場輕食",
    description: "米蘭 Malpensa 機場的咖啡輕食店，供應三明治、可頌與咖啡。出發日早上簡單解決早餐。",
    address: "Malpensa Airport (MXP)",
    hours: "06:00–21:00",
    suggestedTime: "Day 12 出發前早餐",
    price: "€€",
    mustEat: "可頌 + 咖啡",
    rating: "",
    image: "",
    tags: ["機場", "輕食", "早餐"]
  },
  {
    id: 60, city: "米蘭", day: 12,
    name: "Briciole Bar",
    nameEn: "",
    cuisine: "機場輕食",
    description: "米蘭 Malpensa 機場內的義式輕食吧，供應簡單的麵包、咖啡與冷盤。適合候機時享用。",
    address: "Malpensa Airport (MXP)",
    hours: "06:00–21:00",
    suggestedTime: "Day 12 候機時",
    price: "€€",
    mustEat: "義式輕食",
    rating: "",
    image: "",
    tags: ["機場", "輕食", "咖啡"]
  },
  {
    id: 61, city: "米蘭", day: 12,
    name: "Venchi（機場店）",
    nameEn: "",
    cuisine: "巧克力 / Gelato",
    description: "Venchi 在 Malpensa 機場安檢後的免稅區設有專櫃，是最後的義大利伴手禮採購機會。帶幾盒精美巧克力回台灣送禮自用兩相宜。",
    address: "Malpensa Airport, 安檢後免稅區",
    hours: "08:00–20:00",
    suggestedTime: "Day 12 登機前最後採購",
    price: "€",
    mustEat: "手工巧克力禮盒",
    rating: "1878 年創立",
    image: "",
    tags: ["巧克力", "伴手禮", "機場", "1878"]
  }
];
